version: '3'
services:
  mariadb:
    image: mariadb
    restart: always
    volumes:
      - ./SQL/IQuiz.sql:/docker-entrypoint-initdb.d/dump.sql
    environment:
      MYSQL_ROOT_PASSWORD: root
    expose:
      - "3306"
  nginx_identity:
    image: nginx
    ports:
      - "8000:8000"
    volumes:
      - ./Nginx/Identity.conf:/etc/nginx/conf.d/default.conf
  nginx_explorer:
    image: nginx
    ports:
      - "8001:8001"
    volumes:
      - ./Nginx/GwExplorer.conf:/etc/nginx/conf.d/default.conf
  nginx_core:
    image: nginx
    ports:
      - "8002:8002"
    volumes:
      - ./Nginx/GwCore.conf:/etc/nginx/conf.d/default.conf
  nginx_aula:
    image: nginx
    ports:
      - "8003:8003"
    volumes:
      - ./Nginx/GwAula.conf:/etc/nginx/conf.d/default.conf
  identity:
    build: ./Microservices/IdentityService/
    expose:
      - "80"
  gw_explorer:
    build: ./ApiGateway/ExplorerGateway/
    expose:
      - "80"
  gw_core:
    build: ./ApiGateway/CoreGateway/
    expose:
      - "80"
  gw_aula:
    build: ./ApiGateway/AulaGateway/
    expose:
      - "80"
  cuestionario_explorer:
    build: ./Microservices/CuestionarioExplorer/
    expose:
      - "80"
  aula_explorer:
    build: ./Microservices/AulaExplorer/
    expose:
      - "80"
  cuestionario_administracion:
    build: ./Microservices/CuestionarioAdministracion/
    expose:
      - "80"
  prueba_administracion:
    build: ./Microservices/PruebaAdministracion/
    expose:
      - "80"
  asignacion_administracion:
    build: ./Microservices/AsignacionAdministracion/
    expose:
      - "80"
  post_administracion:
    build: ./Microservices/PostAdministracion/
    expose:
      - "80"
  iquiz:
    build: ./IQuiz/
    ports:
      - "80:80"
